<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use App\Models\MasterDDK\MataPencaharian;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MataPencaharianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['mata_pencaharian' => 'Ahli Pengobatan Alternatif ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Akuntan', 'keterangan' => ''],
            ['mata_pencaharian' => 'Anggota kabinet kementrian', 'keterangan' => ''],
            ['mata_pencaharian' => 'Anggota Legislatif', 'keterangan' => ''],
            ['mata_pencaharian' => 'Anggota mahkamah konstitusi ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Apoteker ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Arsitektur/Desainer ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Belum Bekerja', 'keterangan' => ''],
            ['mata_pencaharian' => 'Bidan swasta ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Bupati/walikota', 'keterangan' => ''],
            ['mata_pencaharian' => 'Buruh Harian Lepas ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh jasa perdagangan hasil bumi', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh Migran', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh Tani ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Buruh usaha hotel dan penginapan lainnya', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh usaha jasa hiburan dan pariwisata', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh usaha jasa informasi dan komunikasi', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Buruh usaha jasa transportasi dan perhubungan ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Dokter swasta', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Dosen swasta ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Dukun Tradisional ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Dukun/paranormal/supranatural', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Duta besar ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Gubernur ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Guru swasta', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Ibu Rumah Tangga', 'keterangan' => ''],
            ['mata_pencaharian' => 'Jasa Konsultansi Manajemen dan Teknis', 'keterangan' => ''],
            ['mata_pencaharian' => 'Jasa pengobatan alternatif ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Jasa penyewaan peralatan pesta ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Juru Masak ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Karyawan Honorer ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Karyawan Perusahaan Pemerintah', 'keterangan' => 'besar'],
            ['mata_pencaharian' => 'Karyawan Perusahaan Swasta ', 'keterangan' => 'besar'],
            ['mata_pencaharian' => 'Kepala Daerah ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Konsultan Manajemen dan Teknis', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Kontraktor ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Montir ', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Nelayan', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pedagang barang kelontong', 'keterangan' => ''],
            ['mata_pencaharian' => 'Notaris', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pedagang Keliling', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pegawai Negeri Sipil', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pelajar ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pelaut ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pembantu rumah tangga', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemilik perusahaan ', 'keterangan' => 'besar'],
            ['mata_pencaharian' => 'Pemilik usaha hotel dan penginapan lainnya ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemilik usaha informasi dan komunikasi', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemilik usaha jasa hiburan dan pariwisata ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemilik usaha jasa transportasi dan perhubungan ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemilik usaha warung, rumah makan dan restoran', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pemuka Agama ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pemulung', 'keterangan' => ''],
            ['mata_pencaharian' => 'Penambang ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Peneliti ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pengacara ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pengrajin ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pengrajin industri rumah tangga lainnya ', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Pengusaha kecil, menengah dan besar ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pengusaha perdagangan hasil bumi ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Penyiar radio', 'keterangan' => ''],
            ['mata_pencaharian' => 'Perangkat Desa ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Perawat swasta ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Petani ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Peternak ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pialang ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pilot ', 'keterangan' => ''],
            ['mata_pencaharian' => 'POLRI ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Presiden ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Pskiater/Psikolog ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Purnawirawan/Pensiunan ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Satpam/Security ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Seniman/artis ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Sopir ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Tidak Mempunyai Pekerjaan Tetap ', 'keterangan' => ''],
            ['mata_pencaharian' => 'TNI ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Tukang Anyaman', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Batu', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Cuci ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Tukang Cukur ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Tukang Gigi ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Tukang Jahit ', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Kayu ', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Kue', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Las ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Tukang Listrik ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Tukang Rias', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Tukang Sumur', 'keterangan' => 'kecil'],
            ['mata_pencaharian' => 'Usaha jasa pengerah tenaga kerja ', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Wakil bupati ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Wakil Gubernur', 'keterangan' => ''],
            ['mata_pencaharian' => 'Wartawan ', 'keterangan' => ''],
            ['mata_pencaharian' => 'Wakil presiden', 'keterangan' => ''],
            ['mata_pencaharian' => 'Wiraswasta', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pensiunan TNI/POLRI', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pensiunan Swasta', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Tidak Mempunyai Mata Pencaharian Tetap', 'keterangan' => 'jasa'],
            ['mata_pencaharian' => 'Pensiunan PNS', 'keterangan' => 'jasa'],
        ];

        DB::table('mata_pencaharians')->insert($data);
    }
}
